export default {
  content: {
    title: "Flexible Plans & Pricing",
    text: "Choose the best plan for your needs.",
  },
  plans: [
    {
      name: "professional",
      slug: "professional",
      words: 30000,
      image: 30,
      description: "this is an professional plan",
      price: "9.97",
      billing_cycle: "monthly",
      frequency_unit: 1,
      items: [
        "30, 000 words",
        "30 images",
        "All templates",
        "Unlimited access",
        "Full time support",
      ],
      is_default: true,
      is_popular: false,
    },
    {
      name: "Team",
      slug: "team",
      words: 300000,
      image: 100,
      description: "this is an team plan",
      price: "19.97",
      billing_cycle: "monthly",
      frequency_unit: 1,
      items: [
        "300, 000 words",
        "100 images",
        "All templates",
        "Unlimited access",
        "Full time support",
      ],
      is_default: false,
      is_popular: true,
    },
    {
      name: "Business",
      slug: "business",
      words: 600000,
      image: 200,
      description: "this is an business plan",
      price: "39.97",
      billing_cycle: "monthly",
      frequency_unit: 1,
      items: [
        "600, 000 words",
        "200 images",
        "All templates",
        "Unlimited access",
        "Full time support",
      ],
      is_default: false,
      is_popular: true,
    },
  ],
};
